import './css/style.css'

import { Inter, Architects_Daughter } from 'next/font/google'

import Header from '@/app/(default)/components/ui/header'
import Banner from '@/app/(default)/components/banner'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap',
})

export const metadata = {
  title:
    'Jos. H. Lowenstein &amp; Sons - Leather Products, Hair Products &amp; Fur Products - Dye Products and Dyestuff - JHL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body
        className={`${inter.variable} ${architects_daughter.variable} font-inter antialiased bg-gray-900 text-gray-200 tracking-tight`}
      >
        <div className='flex flex-col min-h-screen overflow-hidden'>
          {/* <Header /> */}
          {children}
          {/* <Banner /> */}
        </div>
      </body>
    </html>
  )
}
